INSERT INTO POKEMON_POKEPASTE.GENDER (ID, NAME) VALUES (1, 'Male');
INSERT INTO POKEMON_POKEPASTE.GENDER (ID, NAME) VALUES (2, 'Female');
INSERT INTO POKEMON_POKEPASTE.GENDER (ID, NAME) VALUES (3, 'Genderless');
