INSERT INTO POKEMON_POKEPASTE.MOVE_CAT (ID, NAME) VALUES (1, 'physical');
INSERT INTO POKEMON_POKEPASTE.MOVE_CAT (ID, NAME) VALUES (2, 'special');
INSERT INTO POKEMON_POKEPASTE.MOVE_CAT (ID, NAME) VALUES (3, 'status');
